;; Generated by :claw at 2021-04-13T19:29:36.340459+03:00
(asdf:defsystem #:cl-dcmtk-bindings
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))))