;; Generated by :claw at 2021-04-12T23:42:47.698330+03:00
(asdf:defsystem #:cl-dcmtk-binding
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))))